spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.20.36.230/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  #设置全局实体类属性值为null时不返回该字段
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 172.20.36.230
    port: 6379

#定义整体项目前缀
server:
  servlet:
    context-path: /sell
  port: 2019



wechat:
  #公众账号，授权
  mpAppId: wx557a6ea91652f1d1
  #mpAppId: wxd898fcb01713c658
  mpAppSecret: 338677634e7f31c11add1cc3314b2a6c
  #开放平台，卖家扫码登录用
  openAppId: 123
  openAppSecret: 123
  #支付/商户号
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  # 发起支付不需要证书，退款需要
  keyPath: /var/weixin_cert/h5.p12
  #异步消息通知
  notifyUrl: http://wxywizard.natapp1.cc/sell/pay/notify
  # 消息模板
  templateId:
    orderStatus: e-cc

projectUrl:
  wechatMpAuthorize: http://lsx888.natapp1.cc
  wechatOpenAuthorize: http://lsx888.natapp1.cc
  sell: http://172.20.36.177:2019